services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - web/.env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - app_network

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    environment:
      - PORT=8000
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
