name: Deploy Remix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DEPLOYING-WEBSITE:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'DEPLOY') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get Instance Public IP
        id: get_ip
        run: |
          INSTANCE_NAME="${{ github.event.repository.name }}"
          INSTANCE_IP=$(aws lightsail get-instance --instance-name $INSTANCE_NAME --query 'instance.publicIpAddress' --output text)
          echo "INSTANCE_IP=${INSTANCE_IP}" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEFAULT_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github
          chmod 600 ~/.ssh/github
          ls -lah ~/.ssh/
          cat ~/.ssh/github | head -n 5  # Debug: Print first 5 lines of SSH key

      - name: SSH into Lightsail Instance and Deploy
        run: |
          echo "Trying to SSH into $INSTANCE_IP..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github ubuntu@${{ env.INSTANCE_IP }} "echo 'SSH connection successful'"

      - name: Run Deployment Script
        run: |
          echo "Deploying application..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github ubuntu@${{ env.INSTANCE_IP }} 'bash -s' < ./deploy.sh
